<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Logica licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->
<wsdl:definitions name='FinishAccountInteraction'
    xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
    xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
    xmlns:xs='http://www.w3.org/2001/XMLSchema'
    xmlns:tjsr='urn:com:logica:se:healthcare:efrikort:administration:FinishAccountResponder:1'
    xmlns:itr='urn:riv:itintegration:registry:1'
    xmlns:tns='urn:com:logica:se:healthcare:efrikort:administration:FinishAccount:1:rivtabp21'
    targetNamespace='urn:com:logica:se:healthcare:efrikort:administration:FinishAccount:1:rivtabp21'>

    <wsdl:documentation xml:lang='sv'>
         Tjänsteinteraktionens namn: FinishAccount
         Beskrivning: 
           Denna tjänst används när en patient vill avsluta sitt konto i eFrikortstjänsten.
           För personnummer som har reservnummer grupperade till sig avser utträdet även de grupperade reservnumren. 
           För grupperat barn avser utträdet endast angivet barn, dvs övriga barn kvarstår i gruppen.
           Utträde medför att uppgifter som avser berörda personidentiteter inte kan nås.
           Utträde görs enbart för angiven frikortstyp.
           Utträde görs för alla vårdhuvudmän.
         Revisioner: 
         Tjänstedomän: efrikort:administration
         Tjänsteinteraktionstyp: Fråga-Svar
         WS-profil: RIVTABP21
         Förvaltas av: Inera AB
    </wsdl:documentation>
    
    <wsdl:types>
        <xs:schema targetNamespace='urn:com:logica:se:healthcare:efrikort:administration:FinishAccount:1:rivtabp21'>
            <xs:import schemaLocation='FinishAccountResponder_1.0.xsd' namespace='urn:com:logica:se:healthcare:efrikort:administration:FinishAccountResponder:1' />
            <xs:import schemaLocation='../../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
        </xs:schema>
    </wsdl:types>
    
        
    <wsdl:message name='FinishAccountRequest'>
        <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
            <wsdl:documentation xml:lang='sv'>http://tempuri.org</wsdl:documentation>
        </wsdl:part>
    
        <wsdl:part name='parameters' element='tjsr:FinishAccountRequest' />
    </wsdl:message>

    <wsdl:message name='FinishAccountResponse'>
        <wsdl:part name='parameters' element='tjsr:FinishAccountResponse' />
    </wsdl:message>

    <wsdl:portType name='FinishAccountResponderInterface'>
        <wsdl:operation name='FinishAccount'>
            <wsdl:input message='tns:FinishAccountRequest' />
            <wsdl:output message='tns:FinishAccountResponse' />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name='FinishAccountResponderBinding' type='tns:FinishAccountResponderInterface'>
        <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
        <wsdl:operation name='FinishAccount'>
            <soap:operation soapAction='urn:com:logica:se:healthcare:efrikort:administration:FinishAccountResponder:1:FinishAccount' style='document' />
            <wsdl:input>
                <soap:header use='literal' message='tns:FinishAccountRequest' part='LogicalAddress' />
                <soap:body use='literal' parts='parameters' />
            </wsdl:input>
            <wsdl:output>
                <soap:body use='literal' />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name='FinishAccountResponderService'>
        <wsdl:port name='FinishAccountResponderPort' binding='tns:FinishAccountResponderBinding'>
            <soap:address location='http://tempuri.org' />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
