<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Logica licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->
<wsdl:definitions name='UngroupPersonInteraction'
    xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
    xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
    xmlns:xs='http://www.w3.org/2001/XMLSchema'
    xmlns:tjsr='urn:com:logica:se:healthcare:efrikort:administration:UngroupPersonResponder:1'
    xmlns:itr='urn:riv:itintegration:registry:1'
    xmlns:tns='urn:com:logica:se:healthcare:efrikort:administration:UngroupPerson:1:rivtabp21'
    targetNamespace='urn:com:logica:se:healthcare:efrikort:administration:UngroupPerson:1:rivtabp21'>

    <wsdl:documentation xml:lang='sv'>
         Tjänsteinteraktionens namn: UngroupPerson
         Beskrivning: 
           Denna tjänst används för att ta bort en personidentitet som är grupperad till ett frikort, oavsett dess status.
           Transaktioner som tillhör personen flyttas över till ett nytt frikort. Status behålls om frikortet är slutgiltigt.
         Revisioner: 
         Tjänstedomän: efrikort:administration
         Tjänsteinteraktionstyp: Fråga-Svar
         WS-profil: RIVTABP21
         Förvaltas av: Inera AB
    </wsdl:documentation>
    
    <wsdl:types>
        <xs:schema targetNamespace='urn:com:logica:se:healthcare:efrikort:administration:UngroupPerson:1:rivtabp21'>
            <xs:import schemaLocation='UngroupPersonResponder_1.0.xsd' namespace='urn:com:logica:se:healthcare:efrikort:administration:UngroupPersonResponder:1' />
            <xs:import schemaLocation='../../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
        </xs:schema>
    </wsdl:types>
    
        
    <wsdl:message name='UngroupPersonRequest'>
        <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
            <wsdl:documentation xml:lang='sv'>http://tempuri.org</wsdl:documentation>
        </wsdl:part>
    
        <wsdl:part name='parameters' element='tjsr:UngroupPersonRequest' />
    </wsdl:message>

    <wsdl:message name='UngroupPersonResponse'>
        <wsdl:part name='parameters' element='tjsr:UngroupPersonResponse' />
    </wsdl:message>

    <wsdl:portType name='UngroupPersonResponderInterface'>
        <wsdl:operation name='UngroupPerson'>
            <wsdl:input message='tns:UngroupPersonRequest' />
            <wsdl:output message='tns:UngroupPersonResponse' />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name='UngroupPersonResponderBinding' type='tns:UngroupPersonResponderInterface'>
        <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
        <wsdl:operation name='UngroupPerson'>
            <soap:operation soapAction='urn:com:logica:se:healthcare:efrikort:administration:UngroupPersonResponder:1:UngroupPerson' style='document' />
            <wsdl:input>
                <soap:header use='literal' message='tns:UngroupPersonRequest' part='LogicalAddress' />
                <soap:body use='literal' parts='parameters' />
            </wsdl:input>
            <wsdl:output>
                <soap:body use='literal' />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name='UngroupPersonResponderService'>
        <wsdl:port name='UngroupPersonResponderPort' binding='tns:UngroupPersonResponderBinding'>
            <soap:address location='http://tempuri.org' />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
